#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
title: Predicting Graffiti using City Layouts
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme
logo: "test.png"
search_enabled: true
