#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
title: Predicting Graffiti using City Layouts
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme
search_enabled: true
aux_links:
  "Predicting Graffiti Using City Layouts on GitHub":
    - "https://github.com/CowKeyMan/PredictingGraffitiUsingCityLayouts"
    
    
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

aux_links_new_tab: true
